docker-deploy/web-app/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rsvp/', include('rsvp.urls')),
    path('rsvp/accounts/', include('django.contrib.auth.urls')),
]

docker-deploy/web-app/rsvp/urls.py
from django.urls import path, include
from django.contrib.auth import logout, login
from . import views
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required

app_name = 'rsvp'
"""
urlpatterns = [
    #ex: /polls/
    path('', views.index, name='index'),
    #ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    #ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    #ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]
"""
urlpatterns = [
    path('accounts/signup/', views.SignUp, name='signup'),
    # rsvp/profile
    path('profile/', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', TemplateView.as_view(template_name='landing.html'), name='landing'),
    # rsvp/events
    path('events_owner/', views.EventOwnerView.as_view(), name = 'event_owner'),
    path('events_vendor/', views.EventVendorView.as_view(), name = 'event_vendor'),
    path('events_guest/', views.EventGuestView.as_view(), name = 'event_guest'),

    path('events_owner/<int:pk>/', views.EventOwnerDetailView.as_view(), name = 'event_owner_detail'),
    path('events_vendor/<int:pk>/', views.EventVendorDetailView.as_view(), name = 'event_vendor_detail'),
    path('events_guest/<int:pk>/', views.event_guest_detail, name = 'event_guest_detail'),
    
    path('events_create/<int:user_id>/', views.event_create, name = 'event_create'),
    path('<int:event_id>/permissions_create/', views.permission_create, name = 'permission_create'),
    path('<int:event_id>/question_create/', views.question_create, name = 'question_create'),
    path('<int:question_id>/question_create/choice_create_index', views.choice_create_index, name = 'choice_create_index'),
    path('<int:question_id>/question_create/choice_create', views.choice_create, name = 'choice_create'),
    path('<int:event_id>/question_create_index/', views.question_create_index, name = 'question_create_index'),
    path('<int:question_id>/question_revise/', views.question_revise, name='question_revise'),
    path('<int:question_id>/question_delete/', views.question_delete, name='question_delete'),
    path('<int:choice_id>/choice_revise/', views.choice_revise, name='choice_revise'),
    path('<int:choice_id>/choice_delete/', views.choice_delete, name='choice_delete'),
    path('<int:permission_id>/guest_answer_index/', views.guest_answer_index, name='guest_answer_index'),
    path('<int:event_id>/notify_question', views.notify_question, name='notify_question'),
    path('<int:choice_id>/notify_choice', views.notify_choice, name='notify_choice'),
    path('<int:question_id>/guest_answer/', views.guest_answer, name='guest_answer'),
    path('<int:question_id>/question_stop/', views.question_stop, name='question_stop'),
    path('<int:response_id>/answer_revise/', views.answer_revise, name='answer_revise'),
    path('<int:question_id>/guest_answer_new/', views.guest_answer_new, name='guest_answer_new'),
    
]
 

docker-deploy/web-app/rsvp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django.forms import EmailField


class Event(models.Model):
	event_name = models.CharField(max_length = 100)
	event_time = models.DateField()
	event_place = models.CharField(max_length = 100)
	potential_users = models.ManyToManyField(User)
	def __str__(self):
		return self.event_name

class Question(models.Model):
	question_text = models.CharField(max_length = 200)
	event = models.ForeignKey(Event, on_delete = models.CASCADE)
	editable = models.BooleanField(default=True)
	vendor_visible = models.BooleanField(default=True)
	freetext = models.BooleanField(default=False)
	def __str__(self):
		return self.event.event_name + "_" + self.question_text
	class Meta:
		ordering = ('question_text',)

class Choice(models.Model):
	choice_text = models.CharField(max_length = 100)
	votes = models.BigIntegerField(default = 0)
	question = models.ForeignKey(Question, on_delete = models.CASCADE)
	def __str__(self):
		return self.choice_text + "_" + self.question.__str__()
	class Meta:
		ordering = ('choice_text',)

class Response(models.Model):
	user = models.ForeignKey(User, on_delete = models.CASCADE)
	choice = models.ForeignKey(Choice, on_delete = models.CASCADE)
	def __str__(self):
		return self.user.username + "_" + self.choice.__str__()

# class ResponseFreetext(models.Model):
# 	user = models.ForeignKey(User, on_delete = models.CASCADE)
# 	freetext = models.CharField(max_length = 500)
# 	question_id = models.BigIntegerField(default = 0)
# 	def __str__(self):
# 		return self.user.username + "_" + self.freetext.__str__()

class Permission(models.Model):
	# one event may correspond to many user statuses (at most 3), and one user status may correspond to many events
	event = models.ForeignKey(Event, on_delete = models.CASCADE)
	# one user may correspond to different statuses in different events, and one status may correspond to many users
	users = models.ManyToManyField(User)
	role = models.CharField(max_length = 10)
	def __str__(self):
		return self.role + "_" + self.event.__str__()
	

# invite guest, vendor, owner
class PermissionForm(ModelForm):
    class Meta:
        model = Permission
        fields = ['users', 'role']

class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = ['event_name', 'event_time', 'event_place']

class QuestionForm(ModelForm):
	class Meta:
		model = Question
		fields = ['question_text', 'vendor_visible', 'freetext']

class ChoiceForm(ModelForm):
	class Meta:
		model = Choice
		fields = ['choice_text']

class MyUserCreationForm(UserCreationForm):
    email = EmailField(label="Email address", required=True,
        help_text="Required")

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

docker-deploy/web-app/rsvp/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import Question, Choice, Event, Permission, Response, PermissionForm, EventForm, QuestionForm, ChoiceForm, MyUserCreationForm
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail

# class SignUp(generic.CreateView):
#     form_class = MyUserCreationForm
#     success_url = reverse_lazy('rsvp:home')
#     template_name = 'signup.html'
#     def form_valid(self, form):
#         self.object = form.save()
#         return super(SignUp, self).form_valid(form) 
def SignUp(request):
    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('rsvp:home'))
        else:
            return HttpResponseRedirect(reverse('rsvp:signup'))
    else:
        form = MyUserCreationForm()
        return render(request, 'signup.html', {'form':form})
    

class EventOwnerView(generic.ListView):
    model = User
    template_name = 'rsvp/event_owner.html'

class EventVendorView(generic.ListView):
    model = User
    template_name = 'rsvp/event_vendor.html'

class EventGuestView(generic.ListView):
    model = User
    template_name = 'rsvp/event_guest.html'

class EventOwnerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Event
    template_name = 'rsvp/event_owner_detail.html'

class EventVendorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Event
    template_name = 'rsvp/event_vendor_detail.html'

def event_guest_detail(request, pk):
    event = Event.objects.get(id = pk)
    responses = Response.objects.filter(user = request.user, choice__question__event = event)
    # questions = [ r.choice.question for r in responses ]
    all_questions = event.question_set.all()
    answered_questions = [r.choice.question for r in responses]
    unanswered_questions = [q for q in all_questions if q not in answered_questions]
    # elem for elem in li if len(elem) > 1
    return render(request, 'rsvp/event_guest_detail.html', {'responses':responses,'unanswered':unanswered_questions})

def question_delete(request, question_id):
    question = Question.objects.get(id = question_id)
    question.delete()
    event = question.event
    return HttpResponseRedirect(reverse('rsvp:event_owner_detail', args=(event.id,)))

def choice_delete(request, choice_id):
    choice = Choice.objects.get(id = choice_id)
    choice.delete()
    event = choice.question.event
    return HttpResponseRedirect(reverse('rsvp:event_owner_detail', args=(event.id,))) 

def permission_create(request, event_id):
    users = User.objects.all()
    event = Event.objects.get(id = event_id)
    form = PermissionForm(request.POST or None)
    if form.is_valid():
        for u in form.cleaned_data['users']:
            if form.cleaned_data['role'] == 'guest':
                event.potential_users.add(u)
                event.save()
            elif form.cleaned_data['role'] == 'vendor':
                perm = event.permission_set.get(role = 'vendor')
                perm.users.add(u)
            else:
                perm = event.permission_set.get(role = 'owner')
                perm.users.add(u)
        return render(request, 'rsvp/finish_create_event.html', {'event': event})
    return render(request, 'rsvp/permission_create.html', {'form': form, 'users': users})

def event_create(request, user_id):
    if request.method == 'POST':
        form = EventForm(request.POST)
        e = form.save();
        p_owner = Permission.objects.create(event=e, role='owner')
        p_owner.save()
        p_owner.users.add(User.objects.get(id = user_id))
        p_vendor = Permission.objects.create(event=e, role='vendor')
        p_vendor.save()
        p_guest = Permission.objects.create(event=e, role='guest')
        p_guest.save()
        return HttpResponseRedirect(reverse('rsvp:question_create_index', args=(e.id,)))
    else:
        form = EventForm()
        return render(request, 'rsvp/event_create.html', {'form': form})

def question_create(request, event_id):
    e = Event.objects.get(id=event_id)
    # if this is a POST request we need to process the form data
    if request.method == 'POST':    
        q = Question.objects.create(event = e)
        form = QuestionForm(request.POST, instance=q)        
        form.save()
        # after finishing question edit, go to choice creation
        if not q.freetext:
            return HttpResponseRedirect(reverse('rsvp:choice_create_index', args=(q.id,)))
        else:
            return HttpResponseRedirect(reverse('rsvp:question_create_index', args=(e.id,)))
    # if a GET (or any other method) we'll create a blank form
    else:
        form = QuestionForm()
        return render(request, 'rsvp/question_create.html', {'form': form})

def notify_question(request, event_id):
    e = Event.objects.get(id=event_id)
    to_email = []
    from_email = request.user.email
    subject = "You got some questions to answer for " + e.event_name
    contact_msg = "Go login your account to answer the new questions!"
    msg='<a href="http://vcm-151.vm.duke.edu:8080/rsvp/accounts/login" target="_blank">Join</a>'
    p = e.permission_set.get(role="guest")
    for user in p.users.all():
        to_email.append(user.email)
    # send to request change choice
    send_mail(subject, contact_msg, from_email, to_email, fail_silently=False, html_message=msg,)
    # return render(request, 'event_owner_detail.html', {'event':e})
    return HttpResponseRedirect(reverse('rsvp:event_owner_detail', args=(e.id,)))

def notify_choice(request, choice_id):
    # q = Question.objects.get(id=question_id)
    choice = Choice.objects.get(id = choice_id)
    choices = choice.question.choice_set.all()
    e = choice.question.event
    to_email = []
    from_email = request.user.email
    subject = "You got some new choices in question " + q.question_text + " for " + e.event_name
    contact_msg = "Go login your account to answer the new questions!"
    msg='<a href="http://vcm-151.vm.duke.edu:8080/rsvp/accounts/login" target="_blank">Join</a>'
    # p = e.permission_set.get(role="guest")
    # for user in p.users.all():
    #     to_email.append(user.email)
    to_email = [r.user for r in choice.response_set.all()]

    # send to request change choice
    send_mail(subject, contact_msg, from_email, to_email, fail_silently=False, html_message=mag,)
    # return render(request, 'event_owner_detail.html', {'event':e})
    return render(request, 'rsvp/choice_create_index.html', {'choices': choices, 'q': q})

def choice_create(request, question_id):
    q = Question.objects.get(id=question_id)
    event_id = q.event.id
    if request.method == 'POST':
        c = Choice.objects.create(question = q)
        form = ChoiceForm(request.POST, instance=c)
        form.save()
        return HttpResponseRedirect(reverse('rsvp:choice_create_index', args=(question_id,)))
    else:
        form = ChoiceForm()
        return render(request, 'rsvp/choice_create.html', {'form':form})

def choice_create_index(request, question_id):
    q = Question.objects.get(id=question_id)
    c = Choice.objects.filter(question = q)
    return render(request, 'rsvp/choice_create_index.html', {'choices': c, 'q':q})

def question_create_index(request, event_id):
    e = Event.objects.get(id=event_id)
    q = Question.objects.filter(event = e)
    return render(request, 'rsvp/question_create_index.html', {'questions': q, 'event':e})

def question_revise(request, question_id):
    q = Question.objects.get(id = question_id)
    event_id = q.event.id
    form = QuestionForm(request.POST or None, instance=q)        
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('rsvp:event_owner_detail', args=(event_id,)))
    return render(request, 'rsvp/question_revise.html', {'form': form})

def choice_revise(request, choice_id):
    c = Choice.objects.get(id = choice_id)
    event_id = c.question.event.id
    form = ChoiceForm(request.POST or None, instance=c)
    if form.is_valid():
        form.save()
        to_email = []
        from_email = request.user.email
        subject = "Choices of " + c.question.question_text + " has been changed!"
        contact_msg = "Go login your account to make new choices!"
        msg='<a href="http://vcm-151.vm.duke.edu:8080/rsvp/accounts/login" target="_blank">Join</a>'
        for r in c.response_set.all():
            to_email.append(r.user.email)
            # send to request change choice
            send_mail(subject, contact_msg, from_email, to_email, fail_silently=False, html_message=msg,)
        return HttpResponseRedirect(reverse('rsvp:event_owner_detail', args=(event_id,)))
    return render(request, 'rsvp/choice_revise.html', {'form':form})

@login_required
def guest_answer_index(request, permission_id):
    p = Permission.objects.get(id=permission_id)
    # register event
    if request.method == 'POST':
        p.users.add(request.user)
        p.event.potential_users.remove(request.user)
        return render(request, 'rsvp/finish_register_event.html')
        # should change to redirect
    else:
        event = p.event
        all_questions = Question.objects.filter(event = event)
        responses = Response.objects.filter(user = request.user, choice__question__event = event)
        answered = [r.choice.question for r in responses]
        unanswered = [q for q in all_questions if q not in answered]
        return render(request, 'rsvp/guest_answer_index.html', {'unanswered': unanswered,

docker-deploy/web-app/templates/rsvp/choice_create.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Choice Create Page{% endblock %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock %}

docker-deploy/web-app/templates/rsvp/choice_create_index.html
<!-- templates/signup.html -->
{% extends 'base.html' %}

{% block title %}Event Question Index{% endblock %}
{% block content %}
  <h2>Created Choices</h2>
  {% for c in choices %}
  	<p>
  		Choice Context: {{ c.choice_text }}
  		<a href="{% url 'rsvp:notify_choice' c.question.id %}"><button>Notify Choice</button></a>
  	</p>
  {% endfor %}
  <p><a href="{% url 'rsvp:choice_create' q.id %}">Create New Choice</a></p>
  <p><a href="{% url 'rsvp:question_create_index' q.event.id%}">Done</a></p>
{% endblock %}

docker-deploy/web-app/templates/rsvp/choice_revise.html
{% extends 'base.html' %}

{% block title %}Choice Revise Page{% endblock %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock %}

docker-deploy/web-app/templates/rsvp/event_guest.html
<!-- templates/home.html-->
{% extends '../base.html' %}

{% block title %}Events Detail{% endblock %}

{% block content %}
  <div class="jumbotron"><h2>You are invited in these events:</h2></div>
  <div class="row" style="display:flex; flex-wrap: wrap;">
  {% for e in user.event_set.all %}
    <div class="col-md-3 col-sm-6">
        <div class="thumbnail">
          <h4>event name: {{e.event_name}}</h4>
          <h4>event place: {{e.event_place}}</h4>
          <h4>event time: {{e.event_time}}</h4>      
          {% for p in e.permission_set.all %}
            {% if p.role == "guest" %}
              <p><a class="btn btn-success" href="{% url 'rsvp:guest_answer_index' p.id %}">Accept Invitation</a></p>
            {% endif %}
          {% endfor %}
        </div>
      </div>    
  {% endfor %}
  </div>
  <div class="jumbotron"><h1>Your events detail:</h1></div>
  <div class="row" style="display:flex; flex-wrap: wrap;">
  {% for p in user.permission_set.all %}
    
    {% if p.role == "guest" %}
    <div class="col-md-3 col-sm-6">
        <div class="thumbnail">
      <h4>Event name:{{ p.event.event_name }}</h4>
      <h4>Event place:{{ p.event.event_place }}</h4>
      <h4>Event time:{{ p.event.event_time }}</h4>
      <h4><a class="btn btn-info" href="{% url 'rsvp:event_guest_detail' p.event.id %}">More info</a></h4>
        </div>
      </div>
    {% endif %}
      
  {% endfor %}
  </div>
{% endblock %}

docker-deploy/web-app/templates/rsvp/event_owner.html
<!-- templates/home.html-->
{% extends '../base.html' %}

{% block title %}Events{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  <div class="jumbotron">
    <h1>Your events list:</h1>
  </div>
  <div class="row text-center" style="display:flex; flex-wrap: wrap;">
  {% for perm in user.permission_set.all %}
  	{% if perm.role == "owner" %}         
      <div class="col-md-3 col-sm-6">
        <div class="thumbnail">
      	<p>Your role is:{{ perm.role }}</p>
      	<p>event name: {{ perm.event.event_name }}</p>
      	<p>event place: {{ perm.event.event_place }}</p>
      	<p>event time: {{ perm.event.event_time }}</p>
        <p><a class="btn btn-info" href="{% url 'rsvp:event_owner_detail' perm.event.id %}">More Info</a></p>
        <p><a class="btn btn-success" href="{% url 'rsvp:permission_create' perm.event.id %}">Invite</a></p> 
      </div>
    </div>      
    {% endif %}
  {% endfor %}
  </div>
  
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}

docker-deploy/web-app/templates/rsvp/event_owner_detail.html
<!-- templates/home.html-->
{% extends '../base.html' %}

{% block title %}Events Owner Detail{% endblock %}

{% block content %}
  <p>Hi {{user.username}}!</p>
  <div>Your events detail:</div>
  {{event.event_name}}
  <p><a href="{% url 'rsvp:question_create' event.id %}">Create Question for this event</a></p>
  <a href="{% url 'rsvp:notify_question' event.id %}"><button>Notify Question</button></a>
  {% for question in event.question_set.all %}
    <p>Question Context: {{ question.question_text }}
      <a class="btn btn-warning" href="{% url 'rsvp:question_revise' question.id %}">Edit Question</a>
      <a class="btn btn-danger" href="{% url 'rsvp:question_delete' question.id %}">Delete Question</a>
      <p>Guest Answer:</p>
      {% for choice in question.choice_set.all %}
        {% if not question.freetext %}
          <li>{{choice.choice_text}}: {{choice.votes}}</li>
        {% else %}
          <li>Guest{{forloop.counter}}:{{choice.choice_text}}</li>
        {% endif %}
      {% endfor %}
	  </p>
    {% if not question.freetext %}
      <p>Choice Context:
  	    {% for choice in question.choice_set.all %}
  	      <p>{{ choice.choice_text }}
            <a class="btn btn-warning" href="{% url 'rsvp:choice_revise' choice.id %}">Edit Choice</a>
  	      	<a class="btn btn-danger" href="{% url 'rsvp:choice_delete' choice.id %}">Delete Choice</a>
  	      </p>
  	    {% endfor %}
  	    <p><a href="{% url 'rsvp:choice_create' question.id %}">Create Choice</a></p>
      </p>
    {% endif %}
  {% endfor %}
{% endblock %}

docker-deploy/web-app/templates/rsvp/event_vendor_detail.html
<!-- templates/home.html-->
{% extends '../base.html' %}

{% block title %}Events Vendor Detail{% endblock %}

{% block content %}
  <p>Hi {{user.username}}!</p>
  <div>Your events detail:</div>
  {{event.event_name}}
  {% for question in event.question_set.all %}
    {% if question.vendor_visible is True %}
      <p>Question Context: {{ question.question_text }}        
          {% for choice in question.choice_set.all %}
            {% if not question.freetext %}
              <li>{{choice.choice_text}}: {{choice.votes}}</li>
            {% else %}
              <li>Guest{{forloop.counter}}:{{choice.choice_text}}</li>
            {% endif %}
          {% endfor %}
          {% if question.editable is True %}
            <a href="{% url 'rsvp:question_stop' question.id %}">Editable</a> 
          {% else %}
            <a href="{% url 'rsvp:question_stop' question.id %}">Uneditable</a>
          {% endif %}
  	  </p>
    {% endif %}
  {% endfor %}
{% endblock %}

docker-deploy/web-app/templates/rsvp/finish_register_event.html
{% extends 'base.html' %}

{% block title %}Finish Registering Event{% endblock %}

{% block content %}
  <h1>Thanks for registering event</h1>
  {% for u in event.potential_users.all %}
    <li>{{u}}</li>
  {% endfor %}

  <p><a href="{% url 'rsvp:home' %}">Go back to home</a></p>
{% endblock %}

docker-deploy/web-app/templates/rsvp/guest_answer.html
{% extends 'base.html' %}

{% block title %}Event Question Index{% endblock %}
{% block content %}
  <h1>{{ question.question_text }}</h1>

{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

{% if not freetext %}
	<form action="" method="post">
		{% csrf_token %}
		{% for choice in question.choice_set.all %}
			<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
			<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
		{% endfor %}
		<input type="submit" value="Vote" />
	</form>
{% else %}
	<form action="" method="post">
		{% csrf_token %}
		<input type="text" name="free_text" placeholder="Enter your answer">
  		<br>
  		<input type="submit" value="Answer" />
	</form>
{% endif %}
{% endblock %}

docker-deploy/web-app/templates/rsvp/guest_answer_index.html
<!-- templates/signup.html -->
{% extends 'base.html' %}

{% block title %}Answer Question Index{% endblock %}
{% block content %}
  <h2>You are going to register {{e.event_name}}!</h2>
  <p>Event place: {{e.event_place}}</p>
  <p>Event time: {{e.event_time}}</p>
  <h2>Answered Questions</h2>
  <div class="row text-center" style="display:flex; flex-wrap: wrap;">
  {% for r in responses %}
    <div class="col-md-3 col-sm-6">
        <div class="thumbnail">
          <p>Question: {{ r.choice.question.question_text }}</p>
          {% if not r.choice.question.freetext %}
            {% for choice in r.choice.question.choice_set.all %}
              {% if r.choice == choice %}
                <li><strong>{{ choice.choice_text }}</strong></li>
              {% else %}
                <li>{{ choice.choice_text }}</li>
              {% endif %}
            {% endfor %}
          {% else %}
            <li>Your answer: {{r.choice.choice_text}}</li>
          {% endif %}
        </div>
      </div>
  {% endfor %}
  </div>
  <p>You haven't answered these questions</p>
  {% for q in unanswered %}
    <p>
      <a href="{% url 'rsvp:guest_answer' q.id %}">{{q.question_text}}</a>
    </p>    
  {% endfor %}
  <form action="" method="POST">{% csrf_token %}
    <input type="submit" value="Save" />
  </form>
{% endblock %}

docker-deploy/web-app/templates/rsvp/permission_create.html
{% extends 'base.html' %}

{% block title %}Permission Create Page{% endblock %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock%}

docker-deploy/web-app/templates/rsvp/question_create.html
{% extends 'base.html' %}

{% block title %}Question Create Page{% endblock %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock %}

docker-deploy/web-app/templates/rsvp/question_create_index.html
<!-- templates/signup.html -->
{% extends 'base.html' %}

{% block title %}Event Question Index{% endblock %}
{% block content %}
  <h1>Event: {{event.event_name}}</h1>
  <h2>You have created these questions</h2>
  {% for q in questions %}
  	<p>Question{{ forloop.counter }}: {{ q.question_text }}</p>
  	<p>Vendor visible: {{ q.vendor_visible }}</p>
    <ul>
      {% for c in q.choice_set.all %}
        <li>choice{{forloop.counter}}: {{c.choice_text}}</li>
      {% endfor %}
    </ul>
  {% endfor %}
  <p><a class="btn btn-success" href="{% url 'rsvp:question_create' event.id %}">Create New Question</a></p>
{% endblock %}

docker-deploy/web-app/templates/rsvp/question_revise.html
{% extends 'base.html' %}

{% block title %}Question Revise Page{% endblock %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock %}