docker-deploy/web-app/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rsvp/', include('rsvp.urls')),
    path('rsvp/accounts/', include('django.contrib.auth.urls')),
]

docker-deploy/web-app/rsvp/urls.py
from django.urls import path, include
from django.contrib.auth import logout, login
from . import views
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required

app_name = 'rsvp'
"""
urlpatterns = [
    #ex: /polls/
    path('', views.index, name='index'),
    #ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    #ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    #ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]
"""
urlpatterns = [
    path('accounts/signup/', views.SignUp, name='signup'),
    # rsvp/profile
    path('profile/', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', TemplateView.as_view(template_name='landing.html'), name='landing'),
    # rsvp/events
    path('events_owner/', views.EventOwnerView.as_view(), name = 'event_owner'),
    path('events_vendor/', views.EventVendorView.as_view(), name = 'event_vendor'),
    path('events_guest/', views.EventGuestView.as_view(), name = 'event_guest'),

    path('events_owner/<int:pk>/', views.EventOwnerDetailView.as_view(), name = 'event_owner_detail'),
    path('events_vendor/<int:pk>/', views.EventVendorDetailView.as_view(), name = 'event_vendor_detail'),
    path('events_guest/<int:pk>/', views.event_guest_detail, name = 'event_guest_detail'),
    
    path('events_create/<int:user_id>/', views.event_create, name = 'event_create'),
    path('<int:event_id>/permissions_create/', views.permission_create, name = 'permission_create'),
    path('<int:event_id>/question_create/', views.question_create, name = 'question_create'),
    path('<int:question_id>/question_create/choice_create_index', views.choice_create_index, name = 'choice_create_index'),
    path('<int:question_id>/question_create/choice_create', views.choice_create, name = 'choice_create'),
    path('<int:event_id>/question_create_index/', views.question_create_index, name = 'question_create_index'),
    path('<int:question_id>/question_revise/', views.question_revise, name='question_revise'),
    path('<int:question_id>/question_delete/', views.question_delete, name='question_delete'),
    path('<int:choice_id>/choice_revise/', views.choice_revise, name='choice_revise'),
    path('<int:choice_id>/choice_delete/', views.choice_delete, name='choice_delete'),
    path('<int:permission_id>/guest_answer_index/', views.guest_answer_index, name='guest_answer_index'),
    path('<int:event_id>/notify_question', views.notify_question, name='notify_question'),
    path('<int:choice_id>/notify_choice', views.notify_choice, name='notify_choice'),
    path('<int:question_id>/guest_answer/', views.guest_answer, name='guest_answer'),
    path('<int:question_id>/question_stop/', views.question_stop, name='question_stop'),
    path('<int:response_id>/answer_revise/', views.answer_revise, name='answer_revise'),
    path('<int:question_id>/guest_answer_new/', views.guest_answer_new, name='guest_answer_new'),
    
]
 

docker-deploy/web-app/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>RSVP Web App</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="/stylesheets/main.css">
  <style>
  body {
      background-image: url("https://images.unsplash.com/photo-1432763597291-6255a042eb30?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=7e6f21cf3a1de0fcaf1bfb6e137ba938&auto=format&fit=crop&w=1351&q=80");
      background-repeat: no-repeat;
      background-size: 100%;
  }
</style>
</head>

<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/rsvp/">RSVP</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li><a href="{% url 'rsvp:home' %}">Signed as {{ user.username }}</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          	<li><a href="{% url 'login' %}">Login</a></li>
            <li><a href="{% url 'rsvp:signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  
  <main>		
		<div class="container">
	    {% block content %}
	    {% endblock %}
      <br >
  			<div><p><a class="btn btn-success" href="{% url 'rsvp:home' %}">Go back home</a><p></div>
  	</div>
  </main>
  
</body>
</html>

docker-deploy/web-app/templates/home.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
	  <h1>
	  	Hi {{ user.username }}!
	  </h1>
	  <div class="row">	  	
	  	<div class="col-md-3 col-sm-6">
	  		<div class="thumbnail">
	  			<img src="https://images.unsplash.com/photo-1505455184862-554165e5f6ba?ixlib=rb-0.3.5&s=66082a26e692337ba5bee0c004d8152e&auto=format&fit=crop&w=1950&q=80">
	  			<div class="caption">
	  				<h4><a href="{% url 'rsvp:event_owner' %}">View owner events</a></h4>
	  			</div>
	  		</div>
	  	</div>
	  	<div class="col-md-3 col-sm-6">
	  		<div class="thumbnail">
	  			<img src="https://images.unsplash.com/photo-1500111709600-7761aa8216c7?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=43e9ffe868fc51695ec6dd718588859b&auto=format&fit=crop&w=1950&q=80">
	  			<div class="caption">
	  				<h4><a href="{% url 'rsvp:event_vendor' %}">View vendor events</a></h4>
	  			</div>
	  		</div>
	  	</div>
	  	<div class="col-md-3 col-sm-6">
	  		<div class="thumbnail">
	  			<img src="https://images.unsplash.com/photo-1476040896332-d84e9246f456?ixlib=rb-0.3.5&s=510a2ec809494109b5491aa3e7decb28&auto=format&fit=crop&w=1350&q=80">
	  			<div class="caption">
	  				<h4><a href="{% url 'rsvp:event_guest' %}">View guest events</a></h4>
	  			</div>
	  		</div>
	  	</div>
	  
	  <p>
	  	<a class="btn btn-success btn-large" href="{% url 'rsvp:event_create' user.id %}">
	  		<span class="glyphicon glyphicon-plus">
	  			
	  		</span>
	  		Create my event!
	  	</a>
	  </p>
	  <p><a class="btn btn-primary" href="{% url 'logout' %}">logout</a></p>
	{% else %}
	  <h1>You are not logged in</h1>
	  <p><a class="btn btn-success" href="{% url 'login' %}">login</a></p>
	{% endif %}

{% endblock %}

<div class="row text-center" style="display:flex; flex-wrap: wrap;">
        <% campgrounds.forEach(function(campground){ %>
            <div class="col-md-3 col-sm-6">
                <div class="thumbnail">
                   <img src="<%= campground.image %>">
                   <div class="caption">
                       <h4><%= campground.name %></h4>
                   </div>
                   <p>
                       <a href="/campgrounds/<%= campground._id %>" class="btn btn-primary">More Info</a>
                   </p>
                </div>
            </div>
        <% }); %>
    </div>

docker-deploy/web-app/templates/landing.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Landing Page{% endblock %}

{% block content %}
<div class="jumbotron">
	<h1>Welcome to Our RSVP Web App</h1>
		<h2>
			Have fun managing your events!
		</h2>
	<div class="row" style="">
		<ul>
			<li>Create you own event</li>
			<li>Register events</li>
			<li>Design questions</li>
			<li>Invite users</li>
		</ul>
	</div>
	<p>
		<a class="btn btn-success btn-large" href="{% url 'rsvp:home' %}">View my events</a>
	</p>
</div>
{% endblock %}

docker-deploy/web-app/templates/signup.html
<!-- templates/signup.html -->
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}